      DOUBLE PRECISION CHIDeZ1, CHIDeZ2 
      DOUBLE PRECISION CHIDeQ1, CHIDeQ2, CHIDeQ3
      DOUBLE PRECISION CHIDeQQ1, CHIDeQQ2, CHIDeQQ3
      DOUBLE PRECISION CHIDePhi1, CHIDePhi2, CHIDePhi3
      DOUBLE PRECISION CHIDeK1(2), CHIDeK2(2), CHIDeK3(2)
      DOUBLE PRECISION CHIDeA1, CHIDeA2, CHIDeB1, CHIDeB2
      DOUBLE PRECISION XI1Min, XI1Max
      DOUBLE PRECISION XI2Min, XI2Max
      DOUBLE PRECISION CHIDeGapMin, CHIDeGapMax
      character*500 CHIDePATH

      
      COMMON /CHIDe/ CHIDeQ1, CHIDeQ2, CHIDeQ3,
     &               CHIDeQQ1, CHIDeQQ2, CHIDeQQ3,
     &               CHIDePhi1, CHIDePhi2, CHIDePhi3,
     &               CHIDeK1, CHIDeK2, CHIDeK3,
     &               CHIDeA1, CHIDeA2, CHIDeB1, CHIDeB2,
     &               CHIDeZ1, CHIDeZ2,
     &               XI1Min, XI1Max,
     &               XI2Min, XI2Max,
     &               CHIDeGapMin, CHIDeGapMax

      COMMON /CHIDeEnv/ CHIDePATH

